# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_auto_20160522_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='brief',
            field=models.TextField(default='a', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='head_img',
            field=models.ImageField(upload_to=b'statics/imgs/upload'),
        ),
    ]
