# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-04 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_auto_20160523_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(related_name='_userprofile_friends_+', to='bbs.UserProfile'),
        ),
    ]
